/**
 * Compliance Report Exporter
 * 
 * Generates and exports compliance reports as PDF (HTML) or CSV.
 * Institution branded, privacy-preserving, read-only data source.
 */

import React, { useState } from 'react';
import { format } from 'date-fns';
import { 
  Download, 
  FileText, 
  FileSpreadsheet, 
  Loader2,
  Calendar,
  Settings,
  Shield,
  CheckCircle,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Calendar as CalendarComponent } from '@/components/ui/calendar';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/contexts/AuthContext';
import { useComplianceReport } from '@/hooks/useComplianceReport';
import { ComplianceReport, ComplianceReportConfig } from '@/types/complianceReport';
import { cn } from '@/lib/utils';

interface ComplianceReportExporterProps {
  className?: string;
}

const ComplianceReportExporter: React.FC<ComplianceReportExporterProps> = ({
  className = '',
}) => {
  const { organization } = useAuth();
  const { generateReport, loading } = useComplianceReport();
  const { toast } = useToast();

  // Date range state
  const [startDate, setStartDate] = useState<Date>(() => {
    const date = new Date();
    date.setDate(date.getDate() - 30);
    return date;
  });
  const [endDate, setEndDate] = useState<Date>(new Date());

  // Report options
  const [includeUptime, setIncludeUptime] = useState(true);
  const [includePolicies, setIncludePolicies] = useState(true);
  const [includeViolations, setIncludeViolations] = useState(true);
  const [includeCompliance, setIncludeCompliance] = useState(true);
  const [reportTitle, setReportTitle] = useState('');

  // Export format
  const [exportFormat, setExportFormat] = useState<'pdf' | 'csv'>('pdf');

  const handleExport = async () => {
    if (!organization) {
      toast({
        title: 'Error',
        description: 'Organization not available',
        variant: 'destructive',
      });
      return;
    }

    const config: ComplianceReportConfig = {
      startDate,
      endDate,
      includeUptime,
      includePolicies,
      includeViolations,
      includeCompliance,
      organizationName: organization.name,
      reportTitle: reportTitle || 'Compliance Report',
    };

    const report = await generateReport(config);
    
    if (!report) {
      toast({
        title: 'Export failed',
        description: 'Failed to generate report data',
        variant: 'destructive',
      });
      return;
    }

    try {
      if (exportFormat === 'csv') {
        downloadCSV(report);
      } else {
        downloadPDF(report);
      }

      toast({
        title: 'Report exported',
        description: `Your ${exportFormat.toUpperCase()} report has been downloaded.`,
      });
    } catch (err) {
      toast({
        title: 'Export failed',
        description: 'Error generating the report file',
        variant: 'destructive',
      });
    }
  };

  const downloadCSV = (report: ComplianceReport) => {
    const rows: string[] = [];
    
    // Header
    rows.push('COMPLIANCE REPORT');
    rows.push(`Organization: ${report.organization.name}`);
    rows.push(`Report Period: ${report.reportPeriod.start} to ${report.reportPeriod.end}`);
    rows.push(`Generated: ${format(new Date(report.generatedAt), 'PPpp')}`);
    rows.push(`Generated By: ${report.generatedBy}`);
    rows.push('');
    
    // Compliance Summary
    rows.push('COMPLIANCE SUMMARY');
    rows.push(`Overall Score: ${report.compliance.overallScore}/100`);
    rows.push(`Trend: ${report.compliance.trend}`);
    rows.push(`Policy Coverage: ${report.compliance.factors.policyCoverage}%`);
    rows.push(`Event Resolution: ${report.compliance.factors.eventResolution}%`);
    rows.push(`Admin Activity: ${report.compliance.factors.adminActivity}%`);
    rows.push('');
    
    // Uptime
    rows.push('ENFORCEMENT UPTIME');
    rows.push(`Average Uptime: ${report.uptime.averageUptime.toFixed(2)}%`);
    rows.push(`Total Hours Monitored: ${report.uptime.totalHoursMonitored}`);
    rows.push(`Downtime Incidents: ${report.uptime.downtimeIncidents}`);
    rows.push('');
    
    // Policies
    rows.push('POLICIES APPLIED');
    rows.push('Title,Type,Enforcement Level,Status,Active Days');
    report.policies.forEach(p => {
      rows.push(`"${p.title}",${p.type},${p.enforcementLevel},${p.status},${p.activeDays}`);
    });
    rows.push('');
    
    // Violations
    rows.push('VIOLATION SUMMARY');
    rows.push(`Total Events: ${report.violations.totalEvents}`);
    rows.push(`Resolved: ${report.violations.resolvedEvents}`);
    rows.push(`Unresolved: ${report.violations.unresolvedEvents}`);
    rows.push(`Resolution Rate: ${report.violations.resolutionRate.toFixed(1)}%`);
    if (report.violations.avgResolutionTimeHours) {
      rows.push(`Avg Resolution Time: ${report.violations.avgResolutionTimeHours.toFixed(1)} hours`);
    }
    rows.push('');
    
    rows.push('EVENTS BY TYPE');
    rows.push('Event Type,Count');
    Object.entries(report.violations.eventsByType).forEach(([type, count]) => {
      rows.push(`"${type.replace(/_/g, ' ')}",${count}`);
    });
    rows.push('');
    
    // Admin Activity
    rows.push('ADMIN ACTIVITY');
    rows.push(`Total Actions: ${report.activity.totalAdminActions}`);
    rows.push(`Active Admins: ${report.activity.activeAdmins}`);
    rows.push('');
    
    rows.push('TOP ACTIONS');
    rows.push('Action,Count');
    report.activity.topActions.forEach(a => {
      rows.push(`"${a.action.replace(/_/g, ' ')}",${a.count}`);
    });
    rows.push('');
    
    // Privacy Statement
    rows.push('PRIVACY STATEMENT');
    rows.push(`"${report.privacyStatement}"`);
    
    const csv = rows.join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance-report-${report.reportPeriod.start}-to-${report.reportPeriod.end}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadPDF = (report: ComplianceReport) => {
    const html = generatePDFHTML(report);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance-report-${report.reportPeriod.start}-to-${report.reportPeriod.end}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generatePDFHTML = (report: ComplianceReport): string => {
    const scoreColor = report.compliance.overallScore >= 80 ? '#059669' : 
                       report.compliance.overallScore >= 60 ? '#d97706' : '#dc2626';
    const scoreBg = report.compliance.overallScore >= 80 ? '#d1fae5' : 
                    report.compliance.overallScore >= 60 ? '#fef3c7' : '#fee2e2';

    return `<!DOCTYPE html>
<html>
<head>
  <title>Compliance Report - ${report.organization.name}</title>
  <style>
    * { box-sizing: border-box; }
    body { 
      font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; 
      padding: 48px; 
      max-width: 900px; 
      margin: 0 auto; 
      color: #1a1a1a; 
      line-height: 1.5;
    }
    
    /* Header */
    .header { 
      border-bottom: 4px solid #0d9488; 
      padding-bottom: 24px; 
      margin-bottom: 32px; 
    }
    .header h1 { 
      color: #0d9488; 
      margin: 0 0 8px 0; 
      font-size: 28px; 
    }
    .header .org-name { 
      font-size: 20px; 
      color: #374151; 
      font-weight: 600; 
      margin-bottom: 16px;
    }
    .meta-grid { 
      display: grid; 
      grid-template-columns: repeat(3, 1fr); 
      gap: 16px; 
      margin-top: 16px; 
    }
    .meta-item { 
      background: #f9fafb; 
      padding: 12px; 
      border-radius: 8px; 
    }
    .meta-label { 
      font-size: 11px; 
      color: #6b7280; 
      text-transform: uppercase; 
      letter-spacing: 0.5px; 
    }
    .meta-value { 
      font-size: 14px; 
      font-weight: 600; 
      color: #1a1a1a; 
    }
    
    /* Sections */
    h2 { 
      color: #374151; 
      font-size: 18px; 
      margin: 32px 0 16px 0; 
      padding-bottom: 8px; 
      border-bottom: 2px solid #e5e7eb; 
    }
    
    /* Compliance Score */
    .score-card { 
      background: linear-gradient(135deg, ${scoreBg} 0%, #fff 100%); 
      border: 2px solid ${scoreColor}; 
      border-radius: 16px; 
      padding: 24px; 
      margin: 24px 0; 
      display: flex; 
      align-items: center; 
      gap: 32px; 
    }
    .score-value { 
      font-size: 56px; 
      font-weight: 800; 
      color: ${scoreColor}; 
    }
    .score-label { 
      font-size: 14px; 
      color: #6b7280; 
    }
    .score-factors { 
      display: grid; 
      gap: 8px; 
      flex: 1; 
    }
    .factor { 
      display: flex; 
      justify-content: space-between; 
      align-items: center; 
      padding: 8px 12px; 
      background: rgba(255,255,255,0.8); 
      border-radius: 8px; 
    }
    .factor-bar { 
      height: 6px; 
      background: #e5e7eb; 
      border-radius: 3px; 
      width: 100px; 
      margin-left: 12px; 
    }
    .factor-fill { 
      height: 100%; 
      background: ${scoreColor}; 
      border-radius: 3px; 
    }
    
    /* Metrics Grid */
    .metrics-grid { 
      display: grid; 
      grid-template-columns: repeat(4, 1fr); 
      gap: 16px; 
      margin: 20px 0; 
    }
    .metric { 
      background: #f9fafb; 
      padding: 20px; 
      border-radius: 12px; 
      border-left: 4px solid #0d9488; 
    }
    .metric-value { 
      font-size: 32px; 
      font-weight: 700; 
      color: #1a1a1a; 
    }
    .metric-label { 
      color: #6b7280; 
      font-size: 13px; 
      margin-top: 4px; 
    }
    
    /* Tables */
    table { 
      width: 100%; 
      border-collapse: collapse; 
      margin: 16px 0; 
      font-size: 14px; 
    }
    th, td { 
      padding: 12px 16px; 
      text-align: left; 
      border-bottom: 1px solid #e5e7eb; 
    }
    th { 
      background: #f9fafb; 
      font-weight: 600; 
      color: #374151;
    }
    tr:last-child td { 
      border-bottom: none; 
    }
    
    /* Status Badges */
    .status-active { 
      background: #d1fae5; 
      color: #059669; 
      padding: 4px 12px; 
      border-radius: 20px; 
      font-size: 12px; 
      font-weight: 600; 
    }
    .status-disabled { 
      background: #f3f4f6; 
      color: #6b7280; 
      padding: 4px 12px; 
      border-radius: 20px; 
      font-size: 12px; 
      font-weight: 600; 
    }
    
    /* Privacy Note */
    .privacy-note { 
      background: #f0fdfa; 
      padding: 20px; 
      border-radius: 12px; 
      margin-top: 40px; 
      border: 1px solid #99f6e4; 
    }
    .privacy-note h3 { 
      color: #0d9488; 
      margin: 0 0 8px 0; 
      font-size: 14px; 
    }
    .privacy-note p { 
      margin: 0; 
      font-size: 13px; 
      color: #374151; 
    }
    
    /* Footer */
    .footer { 
      margin-top: 48px; 
      padding-top: 24px; 
      border-top: 1px solid #e5e7eb; 
      font-size: 11px; 
      color: #9ca3af; 
      text-align: center; 
    }
    
    @media print {
      body { padding: 24px; }
      .score-card { break-inside: avoid; }
      h2 { break-after: avoid; }
      table { break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📊 Compliance Report</h1>
    <div class="org-name">${report.organization.name}</div>
    <div class="meta-grid">
      <div class="meta-item">
        <div class="meta-label">Report Period</div>
        <div class="meta-value">${report.reportPeriod.start} — ${report.reportPeriod.end}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Duration</div>
        <div class="meta-value">${report.reportPeriod.days} days</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Generated</div>
        <div class="meta-value">${format(new Date(report.generatedAt), 'MMM d, yyyy')}</div>
      </div>
    </div>
  </div>

  <div class="score-card">
    <div>
      <div class="score-value">${report.compliance.overallScore}</div>
      <div class="score-label">Compliance Score (out of 100)</div>
    </div>
    <div class="score-factors">
      <div class="factor">
        <span>Policy Coverage</span>
        <span>${report.compliance.factors.policyCoverage}%</span>
        <div class="factor-bar"><div class="factor-fill" style="width: ${report.compliance.factors.policyCoverage}%"></div></div>
      </div>
      <div class="factor">
        <span>Event Resolution</span>
        <span>${report.compliance.factors.eventResolution}%</span>
        <div class="factor-bar"><div class="factor-fill" style="width: ${report.compliance.factors.eventResolution}%"></div></div>
      </div>
      <div class="factor">
        <span>Admin Activity</span>
        <span>${report.compliance.factors.adminActivity}%</span>
        <div class="factor-bar"><div class="factor-fill" style="width: ${report.compliance.factors.adminActivity}%"></div></div>
      </div>
    </div>
  </div>

  <h2>📈 Key Metrics</h2>
  <div class="metrics-grid">
    <div class="metric">
      <div class="metric-value">${report.uptime.averageUptime.toFixed(1)}%</div>
      <div class="metric-label">Average Uptime</div>
    </div>
    <div class="metric">
      <div class="metric-value">${report.violations.totalEvents}</div>
      <div class="metric-label">Total Events</div>
    </div>
    <div class="metric">
      <div class="metric-value">${report.violations.resolutionRate.toFixed(0)}%</div>
      <div class="metric-label">Resolution Rate</div>
    </div>
    <div class="metric">
      <div class="metric-value">${report.activity.activeAdmins}</div>
      <div class="metric-label">Active Admins</div>
    </div>
  </div>

  <h2>📋 Policies Applied</h2>
  <table>
    <thead>
      <tr>
        <th>Policy Name</th>
        <th>Type</th>
        <th>Enforcement</th>
        <th>Status</th>
        <th>Active Days</th>
      </tr>
    </thead>
    <tbody>
      ${report.policies.length > 0 ? report.policies.map(p => `
      <tr>
        <td><strong>${p.title}</strong></td>
        <td>${p.type}</td>
        <td>${p.enforcementLevel}</td>
        <td><span class="status-${p.status}">${p.status}</span></td>
        <td>${p.activeDays}</td>
      </tr>
      `).join('') : '<tr><td colspan="5" style="text-align: center; color: #6b7280;">No policies in this period</td></tr>'}
    </tbody>
  </table>

  <h2>⚠️ Violation Summary</h2>
  <table>
    <thead>
      <tr>
        <th>Event Type</th>
        <th>Count</th>
        <th>% of Total</th>
      </tr>
    </thead>
    <tbody>
      ${Object.entries(report.violations.eventsByType).length > 0 ? 
        Object.entries(report.violations.eventsByType).map(([type, count]) => `
        <tr>
          <td>${type.replace(/_/g, ' ')}</td>
          <td>${count}</td>
          <td>${((count as number / report.violations.totalEvents) * 100).toFixed(1)}%</td>
        </tr>
        `).join('') : 
        '<tr><td colspan="3" style="text-align: center; color: #6b7280;">No events recorded</td></tr>'
      }
    </tbody>
  </table>

  <h2>👥 Admin Activity</h2>
  <table>
    <thead>
      <tr>
        <th>Action</th>
        <th>Count</th>
      </tr>
    </thead>
    <tbody>
      ${report.activity.topActions.length > 0 ?
        report.activity.topActions.map(a => `
        <tr>
          <td>${a.action.replace(/_/g, ' ')}</td>
          <td>${a.count}</td>
        </tr>
        `).join('') :
        '<tr><td colspan="2" style="text-align: center; color: #6b7280;">No admin actions recorded</td></tr>'
      }
    </tbody>
  </table>

  <div class="privacy-note">
    <h3>🔒 Privacy Statement</h3>
    <p>${report.privacyStatement}</p>
  </div>

  <div class="footer">
    Generated by HumanFirst | Report ID: ${report.id} | ${report.generatedAt}
  </div>
</body>
</html>`;
  };

  return (
    <Card className={`glass-card ${className}`}>
      <CardHeader>
        <div className="flex items-center gap-2">
          <Shield className="h-5 w-5 text-primary" />
          <CardTitle className="text-lg">Generate Compliance Report</CardTitle>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Date Range */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label className="text-sm font-medium">Start Date</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    "w-full justify-start text-left font-normal",
                    !startDate && "text-muted-foreground"
                  )}
                >
                  <Calendar className="mr-2 h-4 w-4" />
                  {startDate ? format(startDate, 'PPP') : 'Pick a date'}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <CalendarComponent
                  mode="single"
                  selected={startDate}
                  onSelect={(date) => date && setStartDate(date)}
                  initialFocus
                />
              </PopoverContent>
            </Popover>
          </div>

          <div className="space-y-2">
            <Label className="text-sm font-medium">End Date</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    "w-full justify-start text-left font-normal",
                    !endDate && "text-muted-foreground"
                  )}
                >
                  <Calendar className="mr-2 h-4 w-4" />
                  {endDate ? format(endDate, 'PPP') : 'Pick a date'}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <CalendarComponent
                  mode="single"
                  selected={endDate}
                  onSelect={(date) => date && setEndDate(date)}
                  initialFocus
                />
              </PopoverContent>
            </Popover>
          </div>
        </div>

        {/* Custom Title */}
        <div className="space-y-2">
          <Label className="text-sm font-medium">Report Title (optional)</Label>
          <Input
            placeholder="e.g., Q4 2024 Compliance Report"
            value={reportTitle}
            onChange={(e) => setReportTitle(e.target.value)}
          />
        </div>

        {/* Report Sections */}
        <div className="space-y-3">
          <Label className="text-sm font-medium flex items-center gap-2">
            <Settings className="h-4 w-4" />
            Include Sections
          </Label>
          <div className="grid grid-cols-2 gap-3">
            <div className="flex items-center space-x-2">
              <Checkbox
                id="uptime"
                checked={includeUptime}
                onCheckedChange={(checked) => setIncludeUptime(checked as boolean)}
              />
              <Label htmlFor="uptime" className="text-sm font-normal cursor-pointer">
                Enforcement Uptime
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="policies"
                checked={includePolicies}
                onCheckedChange={(checked) => setIncludePolicies(checked as boolean)}
              />
              <Label htmlFor="policies" className="text-sm font-normal cursor-pointer">
                Policies Applied
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="violations"
                checked={includeViolations}
                onCheckedChange={(checked) => setIncludeViolations(checked as boolean)}
              />
              <Label htmlFor="violations" className="text-sm font-normal cursor-pointer">
                Violation Summary
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="compliance"
                checked={includeCompliance}
                onCheckedChange={(checked) => setIncludeCompliance(checked as boolean)}
              />
              <Label htmlFor="compliance" className="text-sm font-normal cursor-pointer">
                Compliance Score
              </Label>
            </div>
          </div>
        </div>

        {/* Export Format */}
        <div className="space-y-2">
          <Label className="text-sm font-medium">Export Format</Label>
          <Select value={exportFormat} onValueChange={(v) => setExportFormat(v as 'pdf' | 'csv')}>
            <SelectTrigger className="w-full">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="pdf">
                <div className="flex items-center gap-2">
                  <FileText className="h-4 w-4" />
                  PDF Report (HTML)
                </div>
              </SelectItem>
              <SelectItem value="csv">
                <div className="flex items-center gap-2">
                  <FileSpreadsheet className="h-4 w-4" />
                  CSV Spreadsheet
                </div>
              </SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Privacy Notice */}
        <div className="p-3 rounded-lg bg-accent/50 border border-accent">
          <p className="text-xs text-accent-foreground flex items-start gap-2">
            <CheckCircle className="h-4 w-4 mt-0.5 flex-shrink-0" />
            Reports contain aggregate data only. No individual student names or personal information.
          </p>
        </div>

        {/* Export Button */}
        <Button 
          onClick={handleExport} 
          disabled={loading}
          className="w-full"
          size="lg"
        >
          {loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Download className="mr-2 h-4 w-4" />
              Export {exportFormat.toUpperCase()} Report
            </>
          )}
        </Button>
      </CardContent>
    </Card>
  );
};

export default ComplianceReportExporter;
