using Microsoft.Extensions.Logging;
using System.Text.Json;
using System.Text.Json.Serialization;
using ControlPlane.Agent.Models;

namespace ControlPlane.Agent.Services;

/// <summary>
/// Persists domain-usage session data to a JSON file on disk.
/// Called periodically (every 30 s) and on session end.
/// </summary>
public sealed class SessionLogger
{
    private const string DataDirectory = @"C:\ProgramData\ControlPlane";
    private const string LogFileName = "assignment_session_log.json";
    private static readonly string LogFilePath = Path.Combine(DataDirectory, LogFileName);

    private readonly ILogger _logger;
    private readonly JsonSerializerOptions _jsonOptions;
    private readonly SemaphoreSlim _fileLock = new(1, 1);

    public SessionLogger(ILogger logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _jsonOptions = new JsonSerializerOptions
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
        };
    }

    /// <summary>
    /// Writes the current session snapshot to disk.
    /// </summary>
    public async Task PersistAsync(
        Dictionary<string, TimeSpan> domainTimeSpent,
        List<DomainVisitEntry> visitLog,
        CancellationToken cancellationToken = default)
    {
        await _fileLock.WaitAsync(cancellationToken);
        try
        {
            Directory.CreateDirectory(DataDirectory);

            Dictionary<string, JsonElement>? existing = null;
            if (File.Exists(LogFilePath))
            {
                var existingJson = await File.ReadAllTextAsync(LogFilePath, cancellationToken);
                if (!string.IsNullOrWhiteSpace(existingJson))
                {
                    existing = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(existingJson);
                }
            }

            var payload = new SessionLogPayload
            {
                GeneratedAtUtc = DateTime.UtcNow,
                MachineName = Environment.MachineName,
                TotalDomainsVisited = domainTimeSpent.Count,
                DomainSummary = domainTimeSpent
                    .OrderByDescending(kv => kv.Value)
                    .Select(kv => new DomainSummaryEntry
                    {
                        Domain = kv.Key,
                        TotalSeconds = Math.Round(kv.Value.TotalSeconds, 1)
                    })
                    .ToList(),
                Visits = visitLog
                    .OrderBy(v => v.StartTimeUtc)
                    .Select(v => new VisitLogEntry
                    {
                        Domain = v.Domain,
                        StartTimeUtc = v.StartTimeUtc,
                        EndTimeUtc = v.EndTimeUtc,
                        DurationSeconds = Math.Round(v.Duration.TotalSeconds, 1)
                    })
                    .ToList()
            };

            var output = new Dictionary<string, object?>
            {
                ["generatedAtUtc"] = payload.GeneratedAtUtc,
                ["machineName"] = payload.MachineName,
                ["totalDomainsVisited"] = payload.TotalDomainsVisited,
                ["domainSummary"] = payload.DomainSummary,
                ["visits"] = payload.Visits,
            };

            // Keep clipboard/risk events generated by other monitors.
            if (existing is not null)
            {
                if (existing.TryGetValue("clipboardEvents", out var clipboardEvents))
                {
                    output["clipboardEvents"] = clipboardEvents.Deserialize<object>();
                }

                if (existing.TryGetValue("riskEvents", out var riskEvents))
                {
                    output["riskEvents"] = riskEvents.Deserialize<object>();
                }
            }

            var json = JsonSerializer.Serialize(output, _jsonOptions);

            await File.WriteAllTextAsync(LogFilePath, json, cancellationToken);

            _logger.LogDebug("SessionLogger: Persisted {DomainCount} domains, {VisitCount} visits to {Path}",
                payload.TotalDomainsVisited, payload.Visits.Count, LogFilePath);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "SessionLogger: Failed to persist session log to {Path}", LogFilePath);
        }
        finally
        {
            _fileLock.Release();
        }
    }

    public async Task AppendRiskEventAsync(AssignmentRiskLogEvent riskEvent, CancellationToken cancellationToken = default)
    {
        await _fileLock.WaitAsync(cancellationToken);
        try
        {
            Directory.CreateDirectory(DataDirectory);

            Dictionary<string, JsonElement>? existing = null;
            if (File.Exists(LogFilePath))
            {
                var json = await File.ReadAllTextAsync(LogFilePath, cancellationToken);
                if (!string.IsNullOrWhiteSpace(json))
                {
                    existing = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(json);
                }
            }

            existing ??= new Dictionary<string, JsonElement>();

            var riskEvents = new List<AssignmentRiskLogEvent>();
            if (existing.TryGetValue("riskEvents", out var existingRiskEvents))
            {
                var parsed = existingRiskEvents.Deserialize<List<AssignmentRiskLogEvent>>(_jsonOptions);
                if (parsed is not null)
                    riskEvents = parsed;
            }

            riskEvents.Add(riskEvent);
            existing["riskEvents"] = JsonSerializer.SerializeToElement(riskEvents, _jsonOptions);

            var output = JsonSerializer.Serialize(existing, _jsonOptions);
            await File.WriteAllTextAsync(LogFilePath, output, cancellationToken);

            _logger.LogDebug("SessionLogger: Appended risk event {EventType} for domain {Domain}",
                riskEvent.EventType,
                riskEvent.Domain);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "SessionLogger: Failed to append risk event to {Path}", LogFilePath);
        }
        finally
        {
            _fileLock.Release();
        }
    }

    #region JSON DTOs

    private sealed class SessionLogPayload
    {
        public DateTime GeneratedAtUtc { get; init; }
        public string MachineName { get; init; } = string.Empty;
        public int TotalDomainsVisited { get; init; }
        public List<DomainSummaryEntry> DomainSummary { get; init; } = new();
        public List<VisitLogEntry> Visits { get; init; } = new();
    }

    private sealed class DomainSummaryEntry
    {
        public string Domain { get; init; } = string.Empty;
        public double TotalSeconds { get; init; }
    }

    private sealed class VisitLogEntry
    {
        public string Domain { get; init; } = string.Empty;
        public DateTime StartTimeUtc { get; init; }
        public DateTime EndTimeUtc { get; init; }
        public double DurationSeconds { get; init; }
    }

    #endregion
}
