import React, { useMemo, useState } from 'react';
import DashboardLayout from '@/layouts/DashboardLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { supabase } from '@/integrations/supabase/client';

type VerificationResult = {
  verified: boolean;
  tampered: boolean;
  student_name?: string;
  assignment_name?: string;
  exported_at?: string;
  session_integrity?: 'Clean' | 'Suspicious' | 'High Risk';
  violation_count?: number;
  submitted_during_window?: boolean;
  message: string;
};

const VerifySubmissionPage: React.FC = () => {
  const [exportId, setExportId] = useState('');
  const [pdfMetadataText, setPdfMetadataText] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<VerificationResult | null>(null);

  const handleVerify = async () => {
    setLoading(true);
    try {
      const res = await supabase.functions.invoke('verify-export', {
        body: {
          export_id: exportId.trim() || undefined,
          pdf_text: pdfMetadataText.trim() || undefined,
        },
      });
      setResult((res.data || null) as VerificationResult | null);
    } finally {
      setLoading(false);
    }
  };

  const statusVariant = useMemo(() => {
    if (!result) return 'none';
    if (!result.verified || result.tampered) return 'failed';
    if ((result.violation_count || 0) > 0 || result.session_integrity !== 'Clean') return 'warning';
    return 'success';
  }, [result]);

  return (
    <DashboardLayout>
      <div className="mx-auto max-w-4xl space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Verify HumanFirst Assignment</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Drop student&apos;s submitted PDF metadata here or paste Export ID.
            </p>

            <div className="grid gap-2">
              <Label htmlFor="export-id">Enter Export ID manually</Label>
              <Input
                id="export-id"
                value={exportId}
                onChange={(e) => setExportId(e.target.value)}
                placeholder="hf_export_..."
              />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="pdf-metadata">Upload PDF metadata text (XMP extract)</Label>
              <Textarea
                id="pdf-metadata"
                value={pdfMetadataText}
                onChange={(e) => setPdfMetadataText(e.target.value)}
                rows={8}
                placeholder="<humanfirst:export_id>...</humanfirst:export_id>"
              />
            </div>

            <Button onClick={handleVerify} disabled={loading || (!exportId.trim() && !pdfMetadataText.trim())}>
              {loading ? 'Verifying...' : 'Verify Submission'}
            </Button>
          </CardContent>
        </Card>

        {result && (
          <Card className={
            statusVariant === 'success'
              ? 'border-emerald-500/40'
              : statusVariant === 'warning'
                ? 'border-amber-500/40'
                : 'border-red-500/40'
          }>
            <CardHeader>
              <CardTitle>
                {statusVariant === 'success' && '✅ VERIFIED — Authentic HumanFirst Doc'}
                {statusVariant === 'warning' && '✅ VERIFIED — Authentic HumanFirst Doc'}
                {statusVariant === 'failed' && '❌ VERIFICATION FAILED'}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              {result.verified && !result.tampered ? (
                <>
                  <p><strong>Student:</strong> {result.student_name || 'Unknown'}</p>
                  <p><strong>Assignment:</strong> {result.assignment_name || 'Unknown'}</p>
                  <p><strong>Exported:</strong> {result.exported_at ? new Date(result.exported_at).toLocaleString() : 'Unknown'}</p>
                  <p><strong>Session Status:</strong> {result.session_integrity || 'Unknown'}</p>
                  {(result.violation_count || 0) > 0 ? (
                    <p>⚠️ Session had {result.violation_count} violation signals</p>
                  ) : (
                    <p>No violations detected</p>
                  )}
                </>
              ) : (
                <p>
                  This document was not generated by HumanFirst or has been modified after export.
                  Submitted file cannot be trusted.
                </p>
              )}
              <p className="pt-2 text-muted-foreground">{result.message}</p>
            </CardContent>
          </Card>
        )}
      </div>
    </DashboardLayout>
  );
};

export default VerifySubmissionPage;
